name: "rails8_app"

services:
  frontend-client:
    build:
      dockerfile: frontend-client/Dockerfile
    volumes:
      - ../frontend-client:/frontend-client:cached
    ports:
      - "5173:5173"
    command: sleep infinity

  backend:
    build:
      dockerfile: backend/Dockerfile
    volumes:
      - ../backend:/backend:cached
    ports:
      - "3000:3000"
    command: sleep infinity
    depends_on:
      - mysql

  mysql:
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - default

volumes:
  mysql-data:
